# src/main/resources/application.properties
spring.application.name=barberia-backend

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/barberia_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Puerto del servidor (opcional, 8080 es el default)
server.port=8080

# JWT
jwt.secret=123546879845456878dhdjfkdoandjdhajxisoajshdehfjq
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG